[package]
name = "control_panel_gui"
version = "0.1.0"
edition = "2021"
default-run = "ctrl-panel"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.7", package = "gtk4" }
adw = { version = "0.5", package = "libadwaita", features = ["v1_4"] }
clap = { version = "4.4", features = ["derive"] }
regex = "1"
dbus = "0.9"

tokio = {version = "1.0", features = ["rt", "time", "macros"]}
async-channel = "2.3.1"

#givc-client = { git = "https://github.com/tiiuae/ghaf-givc", branch = "main" }
#givc-common = { git = "https://github.com/tiiuae/ghaf-givc", branch = "main" }

givc-client = { git = "https://github.com/avnik/ghaf-givc", branch = "avnik/more-info" }
givc-common = { git = "https://github.com/avnik/ghaf-givc", branch = "avnik/more-info" }

[build-dependencies]
glib-build-tools = "0.18"

[[bin]]
name = "ctrl-panel"
path = "src/main.rs"
